INSERT INTO player VALUES (default, 'Fernando Augusto Giordani', '$2b$10$9O5MsJ0PQoKxSdIDcvIOcuIFZddMH8pCnd6tqZA5jht/9oBpp7iQ.', 'GORDAN', true, true, 'fernando.a.giordani@gmail.com', 'link-avatar');

/* -------------------------------- platform */
INSERT INTO platform VALUES (default, 'Steam (PC)', 'logo-steam');
INSERT INTO platform VALUES (default, 'RetroAchievements', 'logo-retroachievements');
INSERT INTO platform VALUES (default, 'uPlay (PC)', 'logo-uplay');
INSERT INTO platform VALUES (default, 'Origin (PC)', 'logo-origin');
INSERT INTO platform VALUES (default, 'Xbox (PC/Xbox/Xbox 360/Xbox One)', 'logo-xbox');
INSERT INTO platform VALUES (default, 'PlayStation (PS3/PS4)', 'logo-playstation');
INSERT INTO platform VALUES (default, 'Gog.com (PC)', 'logo-gog.com');
INSERT INTO platform VALUES (default, 'In-Game', 'logo-ingame');
INSERT INTO platform VALUES (default, 'Mídia Física', 'logo-midiafisica');
INSERT INTO platform VALUES (default, 'Genérico', 'logo-generico');

/* -------------------------------- TYPE */
INSERT INTO genre VALUES (default, 'Action');
INSERT INTO genre VALUES (default, 'Adventure');
INSERT INTO genre VALUES (default, 'Atmospheric');
INSERT INTO genre VALUES (default, 'Beat em up');
INSERT INTO genre VALUES (default, 'Co-op Offline');
INSERT INTO genre VALUES (default, 'Co-op Online');
INSERT INTO genre VALUES (default, 'Destruction');
INSERT INTO genre VALUES (default, 'Female Protagonist');
INSERT INTO genre VALUES (default, 'Fightning');
INSERT INTO genre VALUES (default, 'FPS (First Person Shooter)');
INSERT INTO genre VALUES (default, 'Gore');
INSERT INTO genre VALUES (default, 'Hack and slash');
INSERT INTO genre VALUES (default, 'Horror');
INSERT INTO genre VALUES (default, 'Indie');
INSERT INTO genre VALUES (default, 'Mature');
INSERT INTO genre VALUES (default, 'Multiplayer');
INSERT INTO genre VALUES (default, 'Open World');
INSERT INTO genre VALUES (default, 'platform');
INSERT INTO genre VALUES (default, 'Psychological');
INSERT INTO genre VALUES (default, 'Puzzle');
INSERT INTO genre VALUES (default, 'Racing');
INSERT INTO genre VALUES (default, 'Realistic');
INSERT INTO genre VALUES (default, 'RPG');
INSERT INTO genre VALUES (default, 'Simulator');
INSERT INTO genre VALUES (default, 'Singleplayer');
INSERT INTO genre VALUES (default, 'Sports');
INSERT INTO genre VALUES (default, 'Stealth');
INSERT INTO genre VALUES (default, 'Survival');
INSERT INTO genre VALUES (default, 'Tactical');
INSERT INTO genre VALUES (default, 'TPS (Third Person Shooter)');
INSERT INTO genre VALUES (default, 'Violent');

/* -------------------------------- GAME */
/* STEAM - GAMES INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, 'A Story About My Uncle', 0);
INSERT INTO game VALUES (default, 'Age of Empires II: HD Edition', 0);
INSERT INTO game VALUES (default, 'Alan Wake', 0);
INSERT INTO game VALUES (default, 'Alan Wake’s American Nightmare', 0);
INSERT INTO game VALUES (default, 'Assassin''s Creed Brotherhood', 0);
INSERT INTO game VALUES (default, 'Assassin''s Creed Origins', 0);
INSERT INTO game VALUES (default, 'Borderlands', 0);
INSERT INTO game VALUES (default, 'Bridge Constructor Portal', 0);
INSERT INTO game VALUES (default, 'Brütal Legend', 0);
INSERT INTO game VALUES (default, 'Bulletstorm', 0);
INSERT INTO game VALUES (default, 'Carmageddon Reincarnation', 0);
INSERT INTO game VALUES (default, 'Clicker Heroes', 0);
INSERT INTO game VALUES (default, 'Counter Strike: Global Offensive', 0);
INSERT INTO game VALUES (default, 'Cubetractor', 0);
INSERT INTO game VALUES (default, 'Darksiders', 0);
INSERT INTO game VALUES (default, 'Dead Rising 2', 0);
INSERT INTO game VALUES (default, 'Deadpool', 0);
INSERT INTO game VALUES (default, 'DiRT 2', 0);
INSERT INTO game VALUES (default, 'DiRT Rally', 0);
INSERT INTO game VALUES (default, 'Dishonored', 0);
INSERT INTO game VALUES (default, 'DOOM', 0);
INSERT INTO game VALUES (default, 'FOTONICA', 0);
INSERT INTO game VALUES (default, 'Goat Simulator', 0);
INSERT INTO game VALUES (default, 'God Mode', 0);
INSERT INTO game VALUES (default, 'Grand Theft Auto V', 0);
INSERT INTO game VALUES (default, 'Halo: Spartan Assault', 0);
INSERT INTO game VALUES (default, 'Hatred', 0);
INSERT INTO game VALUES (default, 'Hellbound: Survival Mode', 0);
INSERT INTO game VALUES (default, 'Heroes of Might & Magic III - HD Edition', 0);
INSERT INTO game VALUES (default, 'HITMAN 2', 0);
INSERT INTO game VALUES (default, 'Jotun: Valhalla Edition', 0);
INSERT INTO game VALUES (default, 'Just Cause', 0);
INSERT INTO game VALUES (default, 'Lead and Gold - Gangs of the Wild West', 0);
INSERT INTO game VALUES (default, 'Left 4 Dead 2', 0);
INSERT INTO game VALUES (default, 'Lords of the Fallen', 0);
INSERT INTO game VALUES (default, 'LYNE', 0);
INSERT INTO game VALUES (default, 'Mad Max', 0);
INSERT INTO game VALUES (default, 'Metro 2033', 0);
INSERT INTO game VALUES (default, 'Mortal Kombat X', 0);
INSERT INTO game VALUES (default, 'OLDTV', 0);
INSERT INTO game VALUES (default, 'Orcs Must Die', 0);
INSERT INTO game VALUES (default, 'OutDrive', 0);
INSERT INTO game VALUES (default, 'PAYDAY: The Heist', 0);
INSERT INTO game VALUES (default, 'PAYDAY 2', 0);
INSERT INTO game VALUES (default, 'Pixel Puzzles Ultimate', 0);
INSERT INTO game VALUES (default, 'POSTAL 2', 0);
INSERT INTO game VALUES (default, 'POSTAL Redux', 0);
INSERT INTO game VALUES (default, 'Praey for the Gods', 0);
INSERT INTO game VALUES (default, 'Quake Champions', 0);
INSERT INTO game VALUES (default, 'Red Orchestra 2: Heroes of Stalingrad', 0);
INSERT INTO game VALUES (default, 'Rise of the Tomb Raider', 0);
INSERT INTO game VALUES (default, 'Rogue Legacy', 0);
INSERT INTO game VALUES (default, 'Sanctum', 0);
INSERT INTO game VALUES (default, 'Shadow Warrior', 0);
INSERT INTO game VALUES (default, 'STAR WARS Jedi Knight II: Jedi Outcast', 0);
INSERT INTO game VALUES (default, 'SUPERHOT', 0);
INSERT INTO game VALUES (default, 'Team Fortress 2', 0);
INSERT INTO game VALUES (default, 'Teenage Mutant Ninja Turtles: Out of the Shadows', 0);
INSERT INTO game VALUES (default, 'The First Tree', 0);
INSERT INTO game VALUES (default, 'Torchlight II', 0);
INSERT INTO game VALUES (default, 'Trackmania² Stadium', 0);
INSERT INTO game VALUES (default, 'Turbo Pug DX', 0);
INSERT INTO game VALUES (default, 'Warframe', 0);
INSERT INTO game VALUES (default, 'Who''s Your Daddy', 0);
INSERT INTO game VALUES (default, 'World of Guns: Gun Disassembly', 0);

/* STEAM - GAMES NOT INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, 'Grand Theft Auto IV', 0);
INSERT INTO game VALUES (default, 'Tom Clancy''s Ghost Recon Future Soldier', 0);

/* STEAM - GAMES THAT HAVE NO MORE TO GET THE ACHIEVEMENTS */
INSERT INTO game VALUES (default, 'Dead Island Epidemic', 0);
INSERT INTO game VALUES (default, 'Nosgoth', 0);


/* RETROACHIEVEMENTS - GAMES - IN PROGRESS */
INSERT INTO game VALUES (default, 'Shadow Dancer: The Secret of Shinobi', 0);
INSERT INTO game VALUES (default, 'Shinobi III: Return of the Ninja Master', 0);
INSERT INTO game VALUES (default, 'Streets of Rage 3', 0);
INSERT INTO game VALUES (default, 'Teenage Mutant Ninja Turtles - The Hyperstone Heist', 0);


/* UPLAY - GAMES INSTALLED - IN PROGRESS */
--INSERT INTO game VALUES (default, 'Assassin''s Creed Brotherhood', 0);
--INSERT INTO game VALUES (default, 'Assassin''s Creed Origins', 0);
INSERT INTO game VALUES (default, 'Rayman Origins', 0);
INSERT INTO game VALUES (default, 'Trackmania² Lagoon', 0);
INSERT INTO game VALUES (default, 'Watch Dogs', 0);

/* UPLAY - GAMES NOT INSTALLED - IN PROGRESS */
--INSERT INTO game VALUES (default, 'Tom Clancy''s Ghost Recon Future Soldier', 0);


/* ORIGIN - GAMES INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, 'Apex Legends', 0);
INSERT INTO game VALUES (default, 'Dead Space 2', 0);

/* ORIGIN - GAMES NOT INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, 'Dead Space 3', 0);
INSERT INTO game VALUES (default, 'Star Wars Battlefront', 0);


/* XBOX - GAMES INSTALLED - IN PROGRESS */
--INSERT INTO game VALUES (default, 'Bulletstorm', 0);
--INSERT INTO game VALUES (default, 'DiRT 2', 0);

/* XBOX - GAMES NOT INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, 'Microsoft Solitaire Collection', 0);
--INSERT INTO game VALUES (default, 'Grand Theft Auto IV', 0);
INSERT INTO game VALUES (default, 'Modern Combat 5: Blackout', 0);
INSERT INTO game VALUES (default, 'Recore', 0);
INSERT INTO game VALUES (default, 'Ruiner', 0);


/* PLAYSTATION - GAMES INSTALLED - IN PROGRESS */
INSERT INTO game VALUES (default, '99 Vidas', 0);
INSERT INTO game VALUES (default, 'Disc Jam', 0);
INSERT INTO game VALUES (default, 'Injustice 2', 0);
INSERT INTO game VALUES (default, 'LEGO Marvel Super Heroes', 0);
--INSERT INTO game VALUES (default, 'Rocket League', 0);
INSERT INTO game VALUES (default, 'Shadow of the Colossus', 0);
INSERT INTO game VALUES (default, 'Uncharted: Drake''s Fortune', 0);
INSERT INTO game VALUES (default, 'Uncharted 3: Drake''s Deception', 0);


/* IN-GAME - GAMES INSTALLED - IN PROGRESS */
--INSERT INTO game VALUES (default, 'Assassin''s Creed Brotherhood', 0);


/* GAMES - ALL platformS - 100% ACHIEVEMENTS */
INSERT INTO game VALUES (default, '#Have a Sticker', 0);
INSERT INTO game VALUES (default, 'Absconding Zatwor', 0);
INSERT INTO game VALUES (default, 'Ace of Words', 0);
INSERT INTO game VALUES (default, 'Achievement Clicker', 0);
INSERT INTO game VALUES (default, 'Achievement Clicker 2018', 0);
INSERT INTO game VALUES (default, 'Achievement Clicker 2019', 0);
INSERT INTO game VALUES (default, 'Alter World', 0);
INSERT INTO game VALUES (default, 'Ampu-Tea', 0);
INSERT INTO game VALUES (default, 'Antenna', 0);
INSERT INTO game VALUES (default, 'Approaching Blocks', 0);
INSERT INTO game VALUES (default, 'Assassin''s Creed', 0);
INSERT INTO game VALUES (default, 'Assassin''s Creed 2', 0);
INSERT INTO game VALUES (default, 'Bad Day', 0);
INSERT INTO game VALUES (default, 'Bell Ringer', 0);
INSERT INTO game VALUES (default, 'BitRay', 0);
INSERT INTO game VALUES (default, 'Blood and Bacon', 0);
INSERT INTO game VALUES (default, 'Bloody Walls', 0);
INSERT INTO game VALUES (default, 'Break Into Zatwor', 0);
--INSERT INTO game VALUES (default, 'Bulletstorm', 0);
INSERT INTO game VALUES (default, 'Burnout Paradise The Ultimate Box', 0);
INSERT INTO game VALUES (default, 'Call of Juarez Gunslinger', 0);
INSERT INTO game VALUES (default, 'Carmageddon', 0);
INSERT INTO game VALUES (default, 'Carmageddon 2: Carpocalypse Now', 0);
INSERT INTO game VALUES (default, 'Carmageddon Splat Pack', 0);
INSERT INTO game VALUES (default, 'Carmageddon TDR 2000', 0);
INSERT INTO game VALUES (default, 'Castle Crashers', 0);
INSERT INTO game VALUES (default, 'Chaos Domain', 0);
INSERT INTO game VALUES (default, 'Chicken Shoot 2', 0);
INSERT INTO game VALUES (default, 'Child of Light', 0);
INSERT INTO game VALUES (default, 'Comix Zone', 0);
INSERT INTO game VALUES (default, 'Dead Bits', 0);
INSERT INTO game VALUES (default, 'Dead Island', 0);
INSERT INTO game VALUES (default, 'Dead Space', 0);
INSERT INTO game VALUES (default, 'Deadlight', 0);
--INSERT INTO game VALUES (default, 'DiRT 2', 0);
INSERT INTO game VALUES (default, 'DiRT 3', 0);
INSERT INTO game VALUES (default, 'DiRT Showdown', 0);
INSERT INTO game VALUES (default, 'Doom 3', 0);
INSERT INTO game VALUES (default, 'Dr. Langeskov, The Tiger, and The Terribly Cursed Emerald: A Whirlwind Heist', 0);
INSERT INTO game VALUES (default, 'Drunk Wizards', 0);
INSERT INTO game VALUES (default, 'Emily is away', 0);
INSERT INTO game VALUES (default, 'Enigma Prison Beta', 0);
INSERT INTO game VALUES (default, 'Escape This', 0);
INSERT INTO game VALUES (default, 'Fall', 0);
INSERT INTO game VALUES (default, 'Far Cry 3', 0);
INSERT INTO game VALUES (default, 'Far Cry 3 Blood Dragon', 0);
INSERT INTO game VALUES (default, 'Fiends of Imprisonment', 0);
INSERT INTO game VALUES (default, 'Five Nights at Freddy''s', 0);
INSERT INTO game VALUES (default, 'Free to Play', 0);
INSERT INTO game VALUES (default, 'God of War', 0);
INSERT INTO game VALUES (default, 'Half-Life', 0);
INSERT INTO game VALUES (default, 'Half-Life: Blue Shift', 0);
INSERT INTO game VALUES (default, 'Half-Life: Opposing Force', 0);
INSERT INTO game VALUES (default, 'Hell Quest', 0);
INSERT INTO game VALUES (default, 'High Hell', 0);
INSERT INTO game VALUES (default, 'HIS (Heroes In the Sky)', 0);
INSERT INTO game VALUES (default, 'Inside', 0);
INSERT INTO game VALUES (default, 'JDM Tuner Racing', 0);
INSERT INTO game VALUES (default, 'LIMBO', 0);
INSERT INTO game VALUES (default, 'Lines by Nestor Yavorskyy', 0);
INSERT INTO game VALUES (default, 'Lines Free by Nestor Yavorskyy', 0);
INSERT INTO game VALUES (default, 'Lines Infinite by Nestor Yavorskyy', 0);
INSERT INTO game VALUES (default, 'Loading Screen Simulator', 0);
INSERT INTO game VALUES (default, 'Make it Indie!', 0);
INSERT INTO game VALUES (default, 'Mandagon', 0);
INSERT INTO game VALUES (default, 'Mark of the Ninja', 0);
INSERT INTO game VALUES (default, 'Mark of the Ninja: Remastered', 0);
INSERT INTO game VALUES (default, 'Mega Man X', 0);
INSERT INTO game VALUES (default, 'Missing Translation', 0);
INSERT INTO game VALUES (default, 'Mr.President', 0);
INSERT INTO game VALUES (default, 'Nail''d', 0);
INSERT INTO game VALUES (default, 'Need for Speed Carbon', 0);
INSERT INTO game VALUES (default, 'Need for Speed Most Wanted (2005)', 0);
INSERT INTO game VALUES (default, 'Need for Speed Most Wanted (2012)', 0);
INSERT INTO game VALUES (default, 'Need for Speed Undercover', 0);
INSERT INTO game VALUES (default, 'Need for Speed Underground 2', 0);
--INSERT INTO game VALUES (default, 'OutDrive', 0);
INSERT INTO game VALUES (default, 'Pointless', 0);
INSERT INTO game VALUES (default, 'Port of Call', 0);
INSERT INTO game VALUES (default, 'Portal', 0);
--INSERT INTO game VALUES (default, 'POSTAL 2', 0);
--INSERT INTO game VALUES (default, 'POSTAL 2', 0); /* GENÉRICO */
INSERT INTO game VALUES (default, 'Q.U.B.E: Director`s Cut', 0);
INSERT INTO game VALUES (default, 'Quake', 0);
INSERT INTO game VALUES (default, 'Quake 2', 0);
INSERT INTO game VALUES (default, 'Quake 2 Mission Pack 1: The Reckoning', 0);
INSERT INTO game VALUES (default, 'Quake 2 Mission Pack 2: Ground Zero', 0);
INSERT INTO game VALUES (default, 'Quake 3 Arena', 0);
INSERT INTO game VALUES (default, 'Quake 3: Team Arena', 0);
INSERT INTO game VALUES (default, 'Quake Mission Pack 1: Scourge of Armagon', 0);
INSERT INTO game VALUES (default, 'Quake Mission Pack 2: Dissolution of Eternity', 0);
INSERT INTO game VALUES (default, 'Rage Parking Simulator 2016', 0);
INSERT INTO game VALUES (default, 'Refunct', 0);
INSERT INTO game VALUES (default, 'RESIDENT EVIL 2 / BIOHAZARD RE:2 "1-Shot Demo"', 0);
INSERT INTO game VALUES (default, 'Retention', 0);
INSERT INTO game VALUES (default, 'Rochard', 0);
INSERT INTO game VALUES (default, 'Rocket League', 0);
--INSERT INTO game VALUES (default, 'Shadow Dancer: The Secret of Shinobi', 0);
--INSERT INTO game VALUES (default, 'Shadow of the Colossus', 0);
INSERT INTO game VALUES (default, 'Shank', 0);
INSERT INTO game VALUES (default, 'Shank 2', 0);
INSERT INTO game VALUES (default, 'Skyreach', 0);
INSERT INTO game VALUES (default, 'Squares', 0);
INSERT INTO game VALUES (default, 'Streets of Rage', 0);
INSERT INTO game VALUES (default, 'Streets of Rage 2', 0);
--INSERT INTO game VALUES (default, 'Streets of Rage 3', 0);
INSERT INTO game VALUES (default, 'Super Lucky''s Tale', 0);
--INSERT INTO game VALUES (default, 'SUPERHOT', 0);
INSERT INTO game VALUES (default, 'SWARMRIDERS', 0);
INSERT INTO game VALUES (default, 'The Culling of the Cows', 0);
INSERT INTO game VALUES (default, 'The Deer', 0);
INSERT INTO game VALUES (default, 'The Orb Chambers', 0);
INSERT INTO game VALUES (default, 'The Plan', 0);
INSERT INTO game VALUES (default, 'The Swapper', 0);
INSERT INTO game VALUES (default, 'The Tape', 0);
INSERT INTO game VALUES (default, 'Tomb Raider (2013)', 0);
INSERT INTO game VALUES (default, 'Tony Hawk''s Pro Skater HD', 0);
INSERT INTO game VALUES (default, 'Transmissions: Element 120', 0);
INSERT INTO game VALUES (default, 'Trine', 0);
INSERT INTO game VALUES (default, 'Turbo Pug', 0);
INSERT INTO game VALUES (default, 'Typoman', 0);
INSERT INTO game VALUES (default, 'Vault of Honor', 0);
INSERT INTO game VALUES (default, 'Viscera Cleanup Detail: Shadow Warrior', 0);
INSERT INTO game VALUES (default, 'Voxelized', 0);
INSERT INTO game VALUES (default, 'WayOut', 0);
INSERT INTO game VALUES (default, 'Yellow: The Yellow Artifact', 0);
INSERT INTO game VALUES (default, 'Zombie Boom', 0);
INSERT INTO game VALUES (default, 'Zup!', 0);
INSERT INTO game VALUES (default, 'Zup! 2', 0);
INSERT INTO game VALUES (default, 'Zup! 3', 0);
INSERT INTO game VALUES (default, 'Zup! 4', 0);
INSERT INTO game VALUES (default, 'Zup! 5', 0);
INSERT INTO game VALUES (default, 'Zup! 6', 0);
INSERT INTO game VALUES (default, 'Zup! 7', 0);
INSERT INTO game VALUES (default, 'Zup! 8', 0);
INSERT INTO game VALUES (default, 'Zup! S', 0);
INSERT INTO game VALUES (default, 'Zup! X', 0);
INSERT INTO game VALUES (default, 'Zup! Zero', 0);

/* -------------------------------- CONTAS*/
INSERT INTO account VALUES (default, 4, 1, 'gordan92', 'GORDAN', 'link-account', 0);
INSERT INTO account VALUES (default, 4, 2, 'fagiordani', 'fagiordani', 'link-account', 233);
INSERT INTO account VALUES (default, 4, 3, 'theDetonator92', 'theDetonator92', 'link-account', 45100);
INSERT INTO account VALUES (default, 4, 4, 'fefeag', 'fefeag', 'link-account', 75);
INSERT INTO account VALUES (default, 4, 5, 'fagiordani', 'fagiordani', 'link-account', 3470);
INSERT INTO account VALUES (default, 4, 5, 'thedetonator92', 'thedetonator92', 'link-account', 865);
INSERT INTO account VALUES (default, 4, 6, 'fagiordani', 'fagiordani', 'link-account', 0);
INSERT INTO account VALUES (default, 4, 7, 'fagiordani', 'fagiordani', 'link-account', 0);
INSERT INTO account VALUES (default, 4, 8, 'fagiordani', 'fagiordani', 'link-account', 0);
INSERT INTO account VALUES (default, 4, 9, 'gordan92-media-fisica', 'GORDAN - Medias Físicas', 'link-account', 0);
INSERT INTO account VALUES (default, 4, 10, 'gordan92-genericos', 'GORDAN - Genéricos', 'link-account', 0);

INSERT INTO status VALUES (default, 'Normal', false);

SELECT
  a.id
  , a.platform_id
  , p.platform
  , a.nickname
  , CASE
	WHEN platform_id = 5
	THEN p.platform||' - ('||a.nickname||') - INSERT INTO account_has_game VALUES (default, '||a.id||', <game_id>, 1, TRUE, 0, 0, 0, 0, 0);'
	ELSE p.platform||' - INSERT INTO account_has_game VALUES (default, '||a.id||', <game_id>, 1, TRUE, 0, 0, 0, 0, 0);'
  END AS insert_ahg
FROM account a
INNER JOIN platform p ON (a.platform_id = p.id);

/* -------------------------------- ACCOUNT_HAS_GAME*/
INSERT INTO account_has_game VALUES (default, 1, 92, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 85, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 1, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 93, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 94, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 95, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 96, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 97, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 2, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 3, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 4, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 98, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 99, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 100, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 77, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 101, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 102, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 103, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 5, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 6, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 104, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 105, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 106, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 107, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 108, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 7, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 109, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 8, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 9, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 10, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 110, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 111, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 112, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 113, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 11, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 114, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 115, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 116, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 117, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 118, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 119, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 12, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 120, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 13, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 14, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 15, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 121, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 122, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 68, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 16, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 123, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 78, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 79, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 124, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 17, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 18, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 125, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 19, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 126, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 86, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 20, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 21, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 127, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 128, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 129, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 130, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 131, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 132, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 133, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 134, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 135, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 136, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 137, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 22, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 138, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 23, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 24, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 139, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 66, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 25, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 140, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 141, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 142, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 26, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 27, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 143, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 28, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 29, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 144, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 145, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 30, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 87, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 146, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 147, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 31, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 32, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 33, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 34, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 88, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 148, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 149, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 150, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 151, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 152, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 35, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 36, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 37, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 153, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 154, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 155, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 156, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 157, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 38, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 81, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 158, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 82, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 39, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 159, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 160, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 161, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 162, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 163, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 164, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 165, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 69, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 40, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 41, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 42, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 44, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 43, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 45, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 166, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 167, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 168, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 46, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 47, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 48, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 169, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 170, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 171, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 172, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 173, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 174, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 175, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 49, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 176, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 177, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 178, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 74, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 83, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 50, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 179, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 180, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 181, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 51, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 182, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 183, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 52, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 84, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 53, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 70, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 89, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 54, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 184, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 185, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 2, 71, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 186, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 187, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 4, 80, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 55, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 188, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 189, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 11, 72, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 190, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 56, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 191, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 57, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 2, 73, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 58, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 192, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 193, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 59, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 194, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 195, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 196, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 197, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 67, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 198, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 199, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 60, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 75, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 61, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 200, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 201, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 202, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 62, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 203, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 91, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 90, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 204, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 205, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 206, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 63, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 76, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 207, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 64, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 65, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 208, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 209, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 210, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 211, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 212, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 213, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 214, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 215, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 216, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 217, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 218, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 219, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 220, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 10, 102, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 103, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 5, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 6, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 5, 10, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 119, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 10, 123, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 10, 78, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 10, 79, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 6, 18, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 127, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 134, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 6, 66, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 1, 46, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 7, 183, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 2, 70, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 2, 72, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 3, 67, 1, TRUE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 8, 201, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 10, 103, 1, FALSE, 0, 0, 0, 0, 0);
INSERT INTO account_has_game VALUES (default, 9, 5, 1, TRUE, 0, 0, 0, 0, 0);
SELECT * FROM account_has_game;

UPDATE game SET name_visualization = 'Carmageddon Max Pack' WHERE id IN (112, 114);
UPDATE game SET name_visualization = 'The Fall' WHERE id IN (133);
UPDATE game SET name_visualization = 'Lines X Free' WHERE id IN (150);
UPDATE game SET name_visualization = 'Lines X' WHERE id IN (149);
UPDATE game SET name_visualization = 'Lines Infinite' WHERE id IN (151);
